#!/bin/bash

success=1

for i in ./testcases/*.in.json; do
    n=${i#./testcases/}; n=${n%.in.json}

    if diff <(./kauma ./testcases/${n}.in.json | jq -S . -) <(jq -S . ./testcases/${n}.out.json); then
        echo "[✔] Test ${n} passed"
    else
        echo "[✘] Test ${n} failed"
        success=0
        if [[ "${1}" == "-e" ]]; then
            exit 1
        fi
    fi
done

if [ $success -eq 1 ]; then
    exit 0
else
    exit 1
fi
